site_name: jackeyt wiki
theme:
    name: 'material'
    
site_author: jackeyt

nav:
- 介绍: index.md
- ARM_Linux驱动入门:
  - 驱动第一天: 驱动第一天---驱动基础.md
  - 驱动第二天: 驱动第二天---中断.md
  - 驱动第三天: 驱动第三天---总线.md
  - 总线的横向对比表: 三种总线的横向对比表.md
  - 驱动第四天: ARMLinux设备树.md
  - 驱动第五天: 手把手教你从单片机移植驱动到ARMLinux上.md
- ARM_Linux应用开发:
  - 0.IDE环境搭建: VSCode搭建ARMLinuxMakefile工程IDE.md
- ARM_Linux内核开发:
  - 0.IDE环境搭建[纯WIN]: VSCode搭建LinuxKernel单步调试IDE环境.md
  - 1.IDE环境搭建[纯Ubuntu]: Ubuntu+VSCode搭建LinuxKernel单步调试IDE环境.md
- 栗子派LeeZ—RK3399试玩:
  - 0.开箱: LeezPi-RK3399_开箱.md
  - 1.SDK使用说明: LeezPi-RK3399_SDK使用.md
  - 2.Android9编译说明: LeezPi-RK3399_Android9编译说明.md
- RK1808S_AI计算棒试玩:
  - 0.开箱: RK1808S_AI计算棒—0.开箱.md
  - 1.开发环境搭建: RK1808S_AI计算棒—1.搭建Windows开发环境.md
  - 2.被动模式下mobilenet_v1模型测试: RK1808S_AI计算棒—2.RK1808被动模式下mobilenet_v1模型测试.md
- HarmonyOS 开发板使用连载:
  - 0.开箱: HarmonyOS开发板使用连载—0.开箱.md


  